const LanguageStore = (function() {
    const dict = {
        'ES': {
            'simTitle': 'Artemis II <span class="light-text">Simulación Simple</span>',
            'successTraj': 'Trayectoria de Éxito',
            'freeReturn': 'Toggle de Retorno Libre',
            'missionStatus': 'Estado: Pre-Lanzamiento',
            'launchParams': 'Parámetros de Lanzamiento Artemis II',
            'launchDate': 'FECHA DE LANZAMIENTO (UTC)',
            'launchVel': 'VELOCIDAD DE LANZAMIENTO (km/s)',
            'launchLocation': 'LUGAR DE LANZAMIENTO',
            'perigee': 'ALTITUD DEL PERIGEO (km)',
            'injectionAngle': 'ÁNGULO TLI OFFSET (°)',
            'btnLaunch': '🚀 LANZAR',
            'btnReset': 'REINICIAR SIMULACIÓN',
            'telemetry': 'Datos de Telemetría (Pre-lanzamiento)',
            'moonPos': 'POSICIÓN LUNA a T+0',
            'successCheck': 'CHEQUEO DE ÉXITO: Pre-Cálculo',
            'ready': 'Listo',
            'hudDist': 'Dist:',
            'hudVel': 'Vel:',
            'modalTitle': 'Ayuda del Simulador Artemis II / Help / Ajuda',
            'helpSec1': '1. Introducción a la Misión y Fenómeno Orbital',
            'helpText1': 'Este simulador ilustra la dinámica de una <b>trayectoria de retorno libre</b> (<i>Free-return trajectory</i>), perfil central de la Misión Artemis II (NASA). La cápsula viaja desde la Tierra mediante inyección translunar (TLI), se adentra en el campo gravitatorio de la cara oculta de la Luna, y la <i>asistencia gravitatoria</i> de dicho cuerpo la frena y redirige automáticamente hacia nuestro planeta en forma de un "8". Todo se calcula en tiempo real bajo un modelo analítico de rotación combinada (CR3BP de N-cuerpos).',
            'helpSec2': '2. Descripción de Controles',
            'helpCont1': '<b>Fecha de Lanzamiento:</b> Determina la fase orbital base de los continentes y el ángulo actual del sistema Tierra-Luna.',
            'helpCont2': '<b>Lugar de Lanzamiento:</b> Selecciona el país. Geométricamente, define el ángulo inercial inicial de inyección.',
            'helpCont3': '<b>Velocidad (km/s):</b> Confiere el impulso delta-v a la nave. En 10.95, y junto a la rotación terrestre, logra el escape exacto hacia la Luna.',
            'helpCont4': '<b>Perigeo (km):</b> Altitud mínima sobre la superficie de origen al momento de inyectarse en órbita.',
            'helpSec3': '3. Dinámica Orbital y Gravitación (CR3BP)',
            'helpText3': 'La Tierra y la Luna se resuelven analíticamente orbitando su <i>Baricentro</i> cruzado. La aceleración inercial vectorial $\\vec{a}$ se calcula utilizando la ley de gravitación universal de Newton para ambos cuerpos atrayendo a la nave simultáneamente:',
            'helpSec4': '4. Modelo Numérico Algorítmico (RK4)',
            'helpRk4_1': 'El motor implementa el algoritmo predictivo no-lineal <i>Runge-Kutta de 4to Órden</i> que evalúa las derivadas en cuatro pasos para lograr una suma estabilizada precisa:',
            'helpRk4_2': 'Garantiza extrema preservación de la energía a lo largo del tiempo, evitando que la nave sufra desvíos matemáticos irreales o caiga en órbitas espirales fantasmas mientras circunvala la Luna.'
        },
        'EN': {
            'simTitle': 'Artemis II <span class="light-text">Simple Simulation</span>',
            'successTraj': 'Success Trajectory',
            'freeReturn': 'Free-return Flyby Toggle',
            'missionStatus': 'Mission Status: Pre-Launch',
            'launchParams': 'Artemis II Launch Parameters',
            'launchDate': 'LAUNCH DATE (UTC)',
            'launchVel': 'LAUNCH VELOCITY (km/s)',
            'launchLocation': 'LAUNCH LOCATION',
            'perigee': 'PERIGEE ALTITUDE (km)',
            'injectionAngle': 'INJECTION ANGLE OFFSET (°)',
            'btnLaunch': '🚀 LAUNCH',
            'btnReset': 'RESET SIMULATION',
            'telemetry': 'Telemetry Data (Pre-launch)',
            'moonPos': 'MOON POSITION at T+0',
            'successCheck': 'SUCCESS CHECK: Pre-Calc',
            'ready': 'Ready',
            'hudDist': 'Dist:',
            'hudVel': 'Vel:',
            'modalTitle': 'Artemis II Simulator Help / Ayuda / Ajuda',
            'helpSec1': '1. Introduction to the Mission & Orbital Phenomenon',
            'helpText1': 'This simulator illustrates the dynamics of a <b>free-return trajectory</b>, the core profile for NASA\'s Artemis II Mission. The capsule travels from Earth via a Trans-Lunar Injection (TLI), enters the gravity well on the far side of the Moon, and uses a gravitational slingshot to brake and safely redirect backward to Earth (a figure-8 shape). Everything is calculated in real-time under an analytical N-Body rotation model (CR3BP).',
            'helpSec2': '2. Launch Controls Description',
            'helpCont1': '<b>Launch Date:</b> Determines the initial orbital phase of the continents and the angle of the Earth-Moon system at T+0.',
            'helpCont2': '<b>Launch Location:</b> Selects the launch country, geometrically defining the initial inertial angular heading.',
            'helpCont3': '<b>Velocity (km/s):</b> Applies the delta-v impulse. Using 10.95 alongside Earth\'s momentum achieves the exact translunar escape.',
            'helpCont4': '<b>Perigee (km):</b> Minimum altitude above the Earth\'s surface upon initial orbit insertion.',
            'helpSec3': '3. Orbital Dynamics & Gravitation (CR3BP)',
            'helpText3': 'Earth and Moon are solved analytically orbiting their mutual <i>Barycenter</i>. The vector inertial acceleration $\\vec{a}$ is calculated using Newton\'s Universal Law of Gravitation for both massive bodies simultaneously:',
            'helpSec4': '4. Algorithmic Numerical Engine (RK4)',
            'helpRk4_1': 'The engine uses the non-linear predictive <i>4th-Order Runge-Kutta</i> algorithm which evaluates derivatives in four steps to achieve specialized stability:',
            'helpRk4_2': 'This guarantees extreme kinetic energy preservation over time, preventing mathematical drift or phantom spiral decay as the ship circumvents the Moon.'
        },
        'PT': {
            'simTitle': 'Artemis II <span class="light-text">Simulação Simples</span>',
            'successTraj': 'Trajetória de Sucesso',
            'freeReturn': 'Toggle Retorno Livre',
            'missionStatus': 'Status da Missão: Pré-Lançamento',
            'launchParams': 'Parâmetros de Lançamento Artemis II',
            'launchDate': 'DATA DE LANÇAMENTO (UTC)',
            'launchVel': 'VELOCIDADE (km/s)',
            'launchLocation': 'LOCAL DE LANÇAMENTO',
            'perigee': 'ALTITUDE DO PERIGEU (km)',
            'injectionAngle': 'ÂNGULO TLI OFFSET (°)',
            'btnLaunch': '🚀 LANÇAR',
            'btnReset': 'REINICIAR SIMULAÇÃO',
            'telemetry': 'Dados de Telemetria (Pré-lançamento)',
            'moonPos': 'POSIÇÃO DA LUA em T+0',
            'successCheck': 'CHECAGEM DE SUCESSO: Pré-Calc',
            'ready': 'Pronto',
            'hudDist': 'Dist:',
            'hudVel': 'Vel:',
            'modalTitle': 'Ajuda do Simulador Artemis II / Help',
            'helpSec1': '1. Introdução à Missão e Fenômeno Orbital',
            'helpText1': 'Este simulador ilustra a dinâmica de uma <b>trajetória de retorno livre</b> (<i>Free-return trajectory</i>), núcleo da Missão Artemis II (NASA). A cápsula viaja da Terra por TLI, entra no campo gravitacional no lado oculto da Lua e ejetada automaticamente graças à <i>assistência gravitacional</i> em forma de "8". Tudo computado ao vivo em modelo analítico CR3BP de N-Corpos.',
            'helpSec2': '2. Controles de Lançamento',
            'helpCont1': '<b>Data de Lançamento:</b> Determina a fase inicial da translação lunar e o vetor base global do momento.',
            'helpCont2': '<b>Lugar de Lançamento:</b> Define geograficamente o ângulo de injeção partindo da superfície.',
            'helpCont3': '<b>Velocidade (km/s):</b> O impulso delta-V somado com o ímpeto inercial do mundo, permitindo precisão translunar ao marcar 10.95.',
            'helpCont4': '<b>Perigeu (km):</b> Altitude sobre a Terra no momento de inserção temporal.',
            'helpSec3': '3. Dinâmica Orbital e Gravitação (CR3BP)',
            'helpText3': 'A Terra e a Lua se movimentam de modo analítico exato circulando em torno do Baricentro gravitacional. A aceleração $\\vec{a}$ resolve-se assim:',
            'helpSec4': '4. Modelo Numérico Algorítmico (RK4)',
            'helpRk4_1': 'O motor emprega a integração não-linear de simulação <i>Runge-Kutta de 4ª Ordem</i> que analisa 4 patamares diferenciais:',
            'helpRk4_2': 'Isto garante 100% de obediência e conservação energética em interações extremas com a gravidade Lunar, impossibilitando erros de escape ou desvios fantasmas de drife.'
        }
    };

    let currentLang = 'EN';

    return {
        getText: function(key) {
            return dict[currentLang][key] || key;
        },
        setLanguage: function(lang) {
            if(dict[lang]) currentLang = lang;
        },
        getCurrent: function() { return currentLang; }
    };
})();
